// Hermes messaging platform gateway

pub mod base;
pub mod channel_directory;
pub mod config;
pub mod cron;
pub mod delivery;
pub mod display_config;
pub mod dispatch;
pub mod formatting;
pub mod hooks;
pub mod mirror;
pub mod pairing;
pub mod platforms;
pub mod restart;
pub mod runner;
pub mod session;
pub mod session_context;
pub mod status;

pub use base::{IncomingMessage, MessageFormat, PlatformAdapter, PlatformConfig, StreamConsumer};
pub use platforms::api_server::{ApiServerAdapter, ApiServerConfig, ApiServerIncomingMessage};
pub use channel_directory::{ChannelDirectory, ChannelInfo};
pub use config::GatewayConfig;
pub use cron::{CronJob, CronScheduler, CronExpr, DeliveryTarget, JobExecution, SchedulerEvent};
pub use cron::{create_job_from_natural, execute_job, parse_natural};
pub use delivery::{Delivery, DeliveryManager, DeliveryStatus, MessageDelivery};
pub use display_config::{DisplayConfig, StickerCache, StickerEntry};
pub use dispatch::dispatch_message;
pub use platforms::email::{EmailAdapter, EmailConfig};
pub use formatting::{format_message, split_message, strip_markdown, truncate};
pub use platforms::sms::{SmsAdapter, SmsConfig};
pub use hooks::{ctx as hook_ctx, GatewayHookType, HookContext, HookRegistry, HookResult};
pub use mirror::{GatewayMirror, MirrorRule, MirroredMessage};
pub use pairing::{PairCode, PairedUser, PairingManager};
pub use platforms::bluebubbles::{BlueBubblesAdapter, BlueBubblesConfig};
pub use platforms::dingtalk::{DingTalkAdapter, DingTalkConfig, DingTalkIncomingMessage};
pub use platforms::discord::{DiscordAdapter, DiscordConfig};
pub use platforms::feishu::{FeishuAdapter, FeishuConfig, FeishuIncomingMessage};
pub use platforms::homeassistant::{HomeAssistantAdapter, HomeAssistantConfig};
pub use platforms::matrix::{MatrixAdapter, MatrixConfig};
pub use platforms::mattermost::{MattermostAdapter, MattermostConfig};
pub use platforms::qqbot::{QqBotAdapter, QqBotConfig, QqBotIncomingMessage};
pub use platforms::signal::{SignalAdapter, SignalConfig};
pub use platforms::slack::{SlackAdapter, SlackConfig};
pub use platforms::telegram::{TelegramAdapter, TelegramConfig};
pub use platforms::telegram_network::{TgNetAdapter, TgNetConfig, TgNetIncomingMessage};
pub use platforms::webhook::WebhookAdapter;
pub use platforms::wecom::{WeComAdapter, WeComConfig, WeComIncomingMessage};
pub use platforms::weixin::{WeixinAdapter, WeixinConfig, WeixinIncomingMessage};
pub use platforms::whatsapp::{WhatsAppAdapter, WhatsAppConfig};
pub use runner::{BufferingConsumer, GatewayRunner, GatewayStatus};
pub use restart::GatewayRestartManager;
pub use session::GatewaySession;
pub use session::GatewaySessionStore;
pub use session_context::{SessionContext, SessionContextTracker};
pub use status::{format_status as format_gateway_status, GatewayStatusInfo, PlatformStatus, StatusTracker};
